### ISSUE TITLE
Unable to load Database

### ISSUE THREAD

**Issue by allannaranjo** [51Degrees/Device-Detection#51]
Error: Allocated continuous memory containing 51Degrees data file appears to be smaller than expected. Most likely because the data file was not fully loaded into the allocated memory

**Comment by jeanlescure** [comment]
We have also tried simplifying to debug, and just running the following code:

```js
const m51d = require('fiftyonedegreescore');

m51d.provider({
  fileName: '/app/vendor/51degrees/51Degrees-EnterpriseV3_2.dat',
  dataFile: '/app/vendor/51degrees/51Degrees-EnterpriseV3_2.dat',
  properties: [
    //...
  ],
});

process.on('uncaughtException', console.error);
```

And got a `SIGSEGV`

Our current `51Degrees-EnterpriseV3_2.dat` as downloaded from the provided download url is 236.0MB

**Comment by jeanlescure** [comment]
Also, we're running `fiftyonedegreescore` version `3.2.24`

**Comment by jeanlescure** [comment]
Following code:

```js
const SegfaultHandler = require('segfault-handler');
SegfaultHandler.registerHandler('crash.log');

const m51d = require('fiftyonedegreescore');

m51d.provider({
  fileName: '/app/vendor/51degrees/51Degrees-EnterpriseV3_2.dat',
  dataFile: '/app/vendor/51degrees/51Degrees-EnterpriseV3_2.dat',
});

process.on('uncaughtException', console.error);
```

Generates following output:

```sh
Error: Allocated continuous memory containing 51Degrees data file appears to be smaller than expected. Most likely because the data file was not fully loaded into the allocated memory.
    at Object.FiftyOneDegrees.provider (/app/node_modules/fiftyonedegreescore/fiftyonedegreescore.js:98:36)
    at Object.<anonymous> (/app/server/index.js:6:6)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
/app/node_modules/fiftyonedegreescore/fiftyonedegreescore.js:109
    returnedProvider.Id = providerId;
                        ^

TypeError: Cannot set property 'Id' of undefined
    at Object.FiftyOneDegrees.provider (/app/node_modules/fiftyonedegreescore/fiftyonedegreescore.js:109:25)
    at Object.<anonymous> (/app/server/index.js:6:6)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by jeanlescure** [comment]
Just in case, the `segfault-handler` reported the following:

```
PID 7 received SIGSEGV for address: 0x0
```

Once I removed the `properties` option from the provider options object, the segmentation fault went away, and I got the previous error:

```
Allocated continuous memory containing 51Degrees data file appears to be smaller than expected. Most likely because the data file was not fully loaded into the allocated memory.
```

**Comment by jeanlescure** [comment]
I understand now that the segmentation fault came from using an array rather than a string on the `properties` option. Putting the appropriate string still generates the error:

```
Allocated continuous memory containing 51Degrees data file appears to be smaller than expected. Most likely because the data file was not fully loaded into the allocated memory.
```

**Comment by Steve51D** [comment]
Hi @jeanlescure , apologies for the delay in getting back to you.

I will pass this to the team to check if there is anything simple you can try.

**Comment by Steve51D** [comment]
It looks like the problem is a corrupt data file. You list the size as 236 Mb, but the data file is currently around 493 Mb.
Could you try downloading it again and verify the MD5 hash of the downloaded file matches the one supplied on the download page.

**Comment by jeanlescure** [comment]
Hi @Steve51D , we arrived at the same conclusion, the thing is we have an automated process that downloads this database (along with others) weekly, since it is crucial for our business to stay up to date.

We are currently having to completely redesign and develop the automated process since the response from the download url has been objectively unreliable (for example, today it took 2 full minutes before the server even transmitted the first byte).

**Comment by jeanlescure** [comment]
Just to add a bit more detail, the downloaded file was not corrupt, per se, but it seems the settings with which the `.gz` file is compressed were changed. Due to this, our automated process only partially decompressed the data file, thankfully our production servers somehow loaded the partially decompressed file without major failure, but it did take a while to simply try a different decompression tool and get the fully decompressed file deployed.

**Comment by jeanlescure** [comment]
In regards to the original issue reported here we detected two errors with hard to diagnose outputs:

1. Placing an array instead of a string on the `properties` option generates a segmentation fault which causes the Node.js process to die instantly
2. A partially decompressed data file generates the error `Allocated continuous memory containing 51Degrees data file appears to be smaller than expected. Most likely because the data file was not fully loaded into the allocated memory.` in some environments and not in others (although in these latter cases the data was still unusable)

Solutions:

1. Make sure `properties` option is a comma delimited string
2. Pre-test decompressed file before deployment, and develop a process that takes into account slow download server response times and transfer

P.D. It would be nice if you guys could just place the database on any sort of CDN for better performance (we'd recommend AWS S3 with Cloudfront and probably a lambda to validate paid users as you currently do)

Cheers

**Comment by Steve51D** [comment]
Hi @jeanlescure, thanks for the feedback.

> today it took 2 full minutes before the server even transmitted the first byte

This will happen when the first request is made for a new data file with your license key. In this situation, a 'master' copy of the new data file exists but the system needs to generate a specific file for you and upload that to the cloud storage system. This is what causes the 2 minute delay. If you request a download again, before a new 'master' file is available, then the delay won't be there because the complete file has already been generated and uploaded to cloud storage for that license key.

> it seems the settings with which the `.gz` file is compressed were changed.

The compression uses the GZipStream class in .NET with the default 'Optimal' compression level. This is unchanged since at least 2016.

> 1. Make sure `properties` option is a comma delimited string

Thanks for this, it would be a sensible change and I'll add it to the backlog. However, our development effort is mostly focused on [version 4](https://github.com/51Degrees/device-detection-node) of the API these days so I can't promise this will ever be implemented.

> 2. Pre-test decompressed file before deployment, and develop a process that takes into account slow download server response times and transfer

We do a lot of testing before release of a new data file. We also use our own device detection API and update service in areas such as our website and internal data processing systems. If there is a significant problem with a new file, we would notice very quickly.

I hear you on the slow response issue. There are certainly things we could do there and I'll add a case to our tracking system for it. That said, it's been this way for years and this is the first I've heard of it causing any trouble so it might be difficult to get development time for it.

> P.D. It would be nice if you guys could just place the database on any sort of CDN for better performance (we'd recommend AWS S3 with Cloudfront and probably a Lambda to validate paid users as you currently do)

As discussed above, we do use a (kind of) CDN - Azure storage. It's just the generation and upload of specific data files for each license key that takes the time.

**Comment by Steve51D** [comment]
I'm closing this due to inactivity. If you have any further questions, please let us know.
